language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
sudo: required
before_script:
  - cp src/main/resources/travis_application.properties src/main/resources/application.properties
services:
  - postgresql
before_install:
  - chmod +x mvnw
  - psql -c "CREATE DATABASE testing_db;" -U postgres
branches:
  only:
    - test
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: e1601133-reactspring